version: '3.9'
services:
  europeana-service-app:
    container_name: europeana-service-app
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - 8000:8000